### ISSUE TITLE
Dhaf.CLI.exe gets an error at startup

### ISSUE THREAD

**Issue by segreich** [hyperion-cs/dhaf#25]
OS: Windows 10 x64, Windows Server 2016
Dhaf: 1.2.2
etcd: 3.5.8

Dhaf.node works fine:
dhaf>dhaf.node --config config-n1.dhaf
←[97m2023-05-04 14:09:57.1963  INFO: Configuration file is <config-n1.dhaf>.←[0m
←[97m2023-05-04 14:09:57.5336  INFO: I am <node1> in the <goros> cluster.←[0m
←[37m2023-05-04 14:09:57.5336 DEBUG: Switcher provider for <main> is <cloudflare>.←[0m
←[37m2023-05-04 14:09:57.5336 DEBUG: Health checker provider for <main> is <web>.←[0m
←[90m2023-05-04 14:09:57.6887 TRACE: [main/web hc] Init process...←[0m
←[97m2023-05-04 14:09:57.7059  INFO: [main/web hc] Init OK.←[0m
←[90m2023-05-04 14:09:57.7138 TRACE: [main/cloudflare sw] Init process...←[0m

 but when i launch Dhaf.CLI.exe it gets error:
dhaf.cli status-services --config config-n1.dhaf

Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Dhaf.CLI.Actions.PrepareRestClient(IConfigPath opt)
   at Dhaf.CLI.Actions.ExecuteStatusServicesAndReturnExitCode(StatusServicesOptions opt)
   at Dhaf.CLI.Program.Main(String[] args)
   at Dhaf.CLI.Program.<Main>(String[] args)

Please help.

**Comment by hyperion-cs** [comment]
Hello, @segreich!
Fixed in version [1.2.2c](https://github.com/hyperion-cs/dhaf/releases/tag/v1.2.2c). Please note that version .NET 5 has been updated to .NET 7 (see release notes).
